In [5]:
import os
import pandas as pd

# Ruta de la carpeta con la extensión
EXTENSION = '.png'
FOLDER_PATH = '/home/nahumfg/GithubProjects/parliament-voting-records/data/procesamiento_todas_votaciones/a_originales'

# Crear lista de archivos (solo nombres, sin full_path)
png_files = [
    {'image_name': f}
    for f in os.listdir(FOLDER_PATH)
    if f.lower().endswith(EXTENSION)
]

# Crear el DataFrame
df_dir_files = pd.DataFrame(png_files)

# Crear columna 'file_name' dividiendo en "_page" (sin incluir) y cambiando extensión a .pdf
df_dir_files['file_name'] = df_dir_files['image_name'].apply(lambda x: x.split('_page')[0] + '.pdf')
df_dir_files = df_dir_files[['file_name']].drop_duplicates()
df_dir_files

                                     file_name
0     91b83996-93b4-5ed6-a364-792b2b094f6f.pdf
1     e1ec821a-74bb-5e3d-8311-5091ae327c54.pdf
2     ec6e778e-28f3-54a3-ad3a-071574fac11c.pdf
3     4b93015a-6096-51f8-bc18-53cc9abc6862.pdf
4     26bf33df-959b-5019-a14b-5f2de70611b4.pdf
...                                        ...
8445  d0e74942-c5b0-54c8-a940-5bcb02208c2d.pdf
8534  01d68ad1-c24d-5744-83f7-d7ec64ea36e9.pdf
8624  34b9621f-fdcb-54de-920e-db7265d7c6da.pdf
8629  93d3d5ff-6dc7-5a10-824e-402a38fa365d.pdf
8689  0e889f6a-5558-56bd-99c8-07167b928864.pdf

[722 rows x 1 columns]

In [10]:
df_nuevos_documentos = pd.read_csv('nuevos_documentos.csv', sep=",", encoding="utf-8")
# Elimina de df_nuevos_documentos todos los 'file_name' que ya están en df_dir_files
df_faltantes = df_nuevos_documentos[~df_nuevos_documentos['file_name'].isin(df_dir_files['file_name'])]
df_faltantes.to_csv('faltantes.csv', header=True, index=False, encoding="utf-8")
df_faltantes

,periodo_parlamentario,periodo_anual,legislatura,descripcion,clean_link,file_name
0,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2025 - 2026,Primera Legislatura Ordinaria,Asistencias y votaciones PROVISIONALES de la s...,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,a90ab077-a704-539b-96fc-d6fc91df3dbd.pdf
1,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2025 - 2026,Primera Legislatura Ordinaria,Asistencias y votación de la sesión del 22-10-...,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,cf308459-8db8-5e34-9352-4c63b559b756.pdf
2,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2025 - 2026,Primera Legislatura Ordinaria,Asistencias y votación de la sesión del 16-10-...,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,ae5c634a-26b6-5ac8-9544-60ae0df44e61.pdf
3,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2025 - 2026,Primera Legislatura Ordinaria,Asistencias y votaciones de la sesión del 10-1...,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,aaf8f003-a271-5ca0-a259-5ceca4de110b.pdf
4,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2025 - 2026,Primera Legislatura Ordinaria,Asistencias y votaciones de la sesión del 9-10...,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,188f59f9-9657-5b53-9e09-5f876d8177f5.pdf
...,...,...,...,...,...,...
921,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2010 - 2011,Primera Legislatura Ordinaria,Asistencias de la sesión del 08-09-2010,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,78730e8e-7d73-52a5-bac9-0672a1dbdee1.pdf
927,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2010 - 2011,Primera Legislatura Ordinaria,Asistencia de la sesión del 28-07-2010,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,879fd557-9d31-51ef-94a8-fdb480720a31.pdf
928,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2010 - 2011,Primera Legislatura Ordinaria,Asistencia de la sesión del 27-07-2010,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,60cfa209-166d-518d-8c37-a717e1885427.pdf
932,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2009 - 2010,Segunda Legislatura Ordinaria,Asistencia de la sesión del 15-06-2010,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,96b00db7-67a0-5d63-9540-da2fb930817d.pdf
934,Congreso de la República - Periodo Parlamentar...,Período Anual de Sesiones 2009 - 2010,Segunda Legislatura Ordinaria,Asistencia de la sesión del 09-06-2010,https://www2.congreso.gob.pe/Sicr/RelatAgenda/...,3f7354f3-a8a3-5e4d-8b4d-9983081787f2.pdf